import type { CreditBand, SourceId, SourceTier, Vertical } from "./types";

// ── Mock lender catalog ──────────────────────────────────────────────────────
// Placeholder inventory standing in for real supply. OppFi products are the
// first-party tier; "engine" lenders simulate Engine by MoneyLion network
// inventory; "partner:*" simulate one-off direct partnerships. Swap these for
// live adapters (Engine rate-table API, etc.) without touching the UI.

export interface MockLender {
  id: string;
  name: string;
  logoText: string;
  brandColor: string;
  rating: number;
  source: SourceId;
  sourceTier: SourceTier;
  isFirstParty: boolean;
  isSponsored: boolean;
  vertical: Vertical;
  /** approved bands, ordered from the lender's core band outward */
  serves: CreditBand[];
  aprByBand: Partial<Record<CreditBand, [number, number]>>;
  term: number; // representative term in months
  amount: [number, number];
  fundingSpeed: string;
  highlights: string[];
  applyUrl: string;
}

export const LENDERS: MockLender[] = [
  // ── First-party: OppFi products ──────────────────────────────────────────
  {
    id: "opploans-installment",
    name: "OppLoans Installment Loan",
    logoText: "OL",
    brandColor: "#005AFF",
    rating: 4.8,
    source: "oppfi",
    sourceTier: "first-party",
    isFirstParty: true,
    isSponsored: false,
    vertical: "personal",
    serves: ["fair", "poor", "good"],
    aprByBand: { good: [59, 99], fair: [79, 140], poor: [110, 160] },
    term: 18,
    amount: [500, 4000],
    fundingSpeed: "As soon as the next business day",
    highlights: ["No prepayment penalty", "Reports to major bureaus", "Same-day decision"],
    applyUrl: "https://www.opploans.com/",
  },
  {
    id: "oppfi-plus-line",
    name: "Opp+ Line of Credit",
    logoText: "O+",
    brandColor: "#0528A0",
    rating: 4.7,
    source: "oppfi",
    sourceTier: "first-party",
    isFirstParty: true,
    isSponsored: false,
    vertical: "personal",
    serves: ["fair", "good", "poor"],
    aprByBand: { good: [49, 89], fair: [69, 120], poor: [99, 149] },
    term: 24,
    amount: [1000, 5000],
    fundingSpeed: "Draw anytime once approved",
    highlights: ["Revolving credit", "Only pay for what you draw", "Builds payment history"],
    applyUrl: "https://www.opploans.com/",
  },

  // ── Direct-premium: a signed one-off partnership (mock) ───────────────────
  {
    id: "reach-financial",
    name: "Reach Financial",
    logoText: "RF",
    brandColor: "#5B4BE0",
    rating: 4.6,
    source: "partner:reach",
    sourceTier: "direct-premium",
    isFirstParty: false,
    isSponsored: true,
    vertical: "personal",
    serves: ["good", "fair"],
    aprByBand: { good: [12.99, 24.99], fair: [24.99, 35.99] },
    term: 36,
    amount: [3500, 40000],
    fundingSpeed: "1–3 business days",
    highlights: ["Debt-consolidation specialist", "Direct payoff to creditors"],
    applyUrl: "https://example.com/reach",
  },

  // ── Network: simulated Engine by MoneyLion inventory ──────────────────────
  {
    id: "sofi",
    name: "SoFi",
    logoText: "SF",
    brandColor: "#00A0DF",
    rating: 4.8,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["excellent", "good"],
    aprByBand: { excellent: [8.99, 15.99], good: [13.99, 22.99] },
    term: 48,
    amount: [5000, 100000],
    fundingSpeed: "Same day possible",
    highlights: ["No fees required", "Unemployment protection"],
    applyUrl: "https://example.com/sofi",
  },
  {
    id: "upstart",
    name: "Upstart",
    logoText: "UP",
    brandColor: "#3FB68B",
    rating: 4.7,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["good", "fair", "excellent"],
    aprByBand: { excellent: [9.99, 18.99], good: [15.99, 28.99], fair: [25.99, 35.99] },
    term: 36,
    amount: [1000, 50000],
    fundingSpeed: "Next business day",
    highlights: ["AI underwriting", "Accepts thinner credit files"],
    applyUrl: "https://example.com/upstart",
  },
  {
    id: "upgrade",
    name: "Upgrade",
    logoText: "UG",
    brandColor: "#FF6B4A",
    rating: 4.6,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["good", "fair"],
    aprByBand: { good: [14.99, 26.99], fair: [24.99, 35.99] },
    term: 36,
    amount: [1000, 50000],
    fundingSpeed: "Within a day of approval",
    highlights: ["Fixed rates", "Direct payoff option"],
    applyUrl: "https://example.com/upgrade",
  },
  {
    id: "best-egg",
    name: "Best Egg",
    logoText: "BE",
    brandColor: "#E8B21E",
    rating: 4.6,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["good", "excellent"],
    aprByBand: { excellent: [8.99, 16.99], good: [14.99, 25.99] },
    term: 36,
    amount: [2000, 50000],
    fundingSpeed: "1–3 business days",
    highlights: ["Top-rated service", "Secured option available"],
    applyUrl: "https://example.com/bestegg",
  },
  {
    id: "lendingpoint",
    name: "LendingPoint",
    logoText: "LP",
    brandColor: "#2FA37C",
    rating: 4.4,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["fair", "good"],
    aprByBand: { good: [17.99, 29.99], fair: [26.99, 35.99] },
    term: 30,
    amount: [2000, 36500],
    fundingSpeed: "As soon as next day",
    highlights: ["Flexible terms", "Works with fair credit"],
    applyUrl: "https://example.com/lendingpoint",
  },
  {
    id: "avant",
    name: "Avant",
    logoText: "AV",
    brandColor: "#3B8BEB",
    rating: 4.3,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["fair", "poor"],
    aprByBand: { fair: [24.99, 35.99], poor: [34.99, 45.99] },
    term: 36,
    amount: [2000, 35000],
    fundingSpeed: "Next business day",
    highlights: ["Built for fair credit", "Mobile-first servicing"],
    applyUrl: "https://example.com/avant",
  },

  // ── Overflow: aggregator-sourced fill (mock) ──────────────────────────────
  {
    id: "prosper",
    name: "Prosper",
    logoText: "PR",
    brandColor: "#00B0A6",
    rating: 4.2,
    source: "engine",
    sourceTier: "overflow",
    isFirstParty: false,
    isSponsored: false,
    vertical: "personal",
    serves: ["good", "fair"],
    aprByBand: { good: [16.99, 27.99], fair: [26.99, 35.99] },
    term: 36,
    amount: [2000, 50000],
    fundingSpeed: "1–3 business days",
    highlights: ["Peer-to-peer", "Joint applications"],
    applyUrl: "https://example.com/prosper",
  },

  // ── A couple of other verticals so category pages have inventory ──────────
  {
    id: "oppfi-auto",
    name: "OppLoans Auto Cash",
    logoText: "OL",
    brandColor: "#005AFF",
    rating: 4.6,
    source: "oppfi",
    sourceTier: "first-party",
    isFirstParty: true,
    isSponsored: false,
    vertical: "auto",
    serves: ["fair", "poor", "good"],
    aprByBand: { good: [39, 79], fair: [59, 110], poor: [89, 149] },
    term: 24,
    amount: [1000, 6000],
    fundingSpeed: "Next business day",
    highlights: ["Use your vehicle value", "No prepayment penalty"],
    applyUrl: "https://www.opploans.com/",
  },
  {
    id: "carvana-auto",
    name: "Carvana Financing",
    logoText: "CV",
    brandColor: "#2C7BE5",
    rating: 4.5,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "auto",
    serves: ["excellent", "good", "fair"],
    aprByBand: { excellent: [6.99, 12.99], good: [11.99, 19.99], fair: [18.99, 27.99] },
    term: 60,
    amount: [5000, 75000],
    fundingSpeed: "Instant pre-approval",
    highlights: ["Shop + finance together", "Real terms up front"],
    applyUrl: "https://example.com/carvana",
  },
  {
    id: "oppfi-card",
    name: "Opp+ Card",
    logoText: "O+",
    brandColor: "#0528A0",
    rating: 4.5,
    source: "oppfi",
    sourceTier: "first-party",
    isFirstParty: true,
    isSponsored: false,
    vertical: "card",
    serves: ["fair", "poor", "good"],
    aprByBand: { good: [29.99, 34.99], fair: [34.99, 35.99], poor: [35.99, 35.99] },
    term: 0,
    amount: [300, 1500],
    fundingSpeed: "Instant decision",
    highlights: ["Builds credit", "No security deposit", "Reports to all 3 bureaus"],
    applyUrl: "https://www.opploans.com/",
  },
  {
    id: "petal-card",
    name: "Petal 2 Card",
    logoText: "PT",
    brandColor: "#6C5CE7",
    rating: 4.4,
    source: "engine",
    sourceTier: "network",
    isFirstParty: false,
    isSponsored: false,
    vertical: "card",
    serves: ["good", "fair"],
    aprByBand: { good: [18.99, 28.99], fair: [26.99, 32.99] },
    term: 0,
    amount: [500, 10000],
    fundingSpeed: "Instant decision",
    highlights: ["No annual fee", "Cash back on select merchants"],
    applyUrl: "https://example.com/petal",
  },
];
